In [1]:
import pandas as pd
import seaborn as sb
import tensorflow as tf

df= pd.read_csv("data/Ca_fire_weather.csv")
df

Unnamed: 0  AcresBurned  ArchiveYear  Precip (in)  Days Burned  \
0             0     410203.0          0.0          0.0     0.447222   
1             1      48920.0          0.0          0.0     0.447222   
2             2         75.0          0.0          0.0     0.511111   
3             3        972.0          0.0          0.0     0.436111   
4             4         90.0          0.0          0.0     0.508333   
..          ...          ...          ...          ...          ...   
444         444         13.0          1.0          0.0     0.002778   
445         445         11.0          1.0          0.0     0.000000   
446         446         11.0          1.0          0.0     0.000000   
447         447         10.0          1.0          0.0     0.000000   
448         448         10.0          1.0          1.0     0.022222   

     Precipitation  Temperature  Humidity  Wind Speed  CalFireIncident 0  ...  \
0         0.075170     0.694110  0.769694    0.286721                0.0  ...   
1         0.075170     0.694110  0.769694    0.286721                0.0  ...   
2         0.066545     0.715255  0.770036    0.283663                0.0  ...   
3         0.000000     0.000000  0.000000    0.000000                1.0  ...   
4         0.092783     0.834265  0.591071    0.242949                0.0  ...   
..             ...          ...       ...         ...                ...  ...   
444       0.019330     0.917902  0.386905    0.336538                0.0  ...   
445       0.000000     0.831243  0.750000    0.160256                0.0  ...   
446       0.000000     0.751425  0.916667    0.211538                0.0  ...   
447       0.000000     0.866591  0.440476    0.198718                0.0  ...   
448       0.000000     0.713164  0.727513    0.162393                0.0  ...   

     CIMIS Region 2  CIMIS Region 3  CIMIS Region 4  CIMIS Region 5  \
0               0.0             0.0             0.0             0.0   
1               0.0             0.0             0.0             0.0   
2               0.0             0.0             0.0             0.0   
3               0.0             0.0             1.0             0.0   
4               0.0             0.0             1.0             0.0   
..              ...             ...             ...             ...   
444             0.0             0.0             0.0             0.0   
445             0.0             0.0             0.0             0.0   
446             0.0             0.0             0.0             0.0   
447             0.0             0.0             0.0             0.0   
448             0.0             0.0             0.0             0.0   

     CIMIS Region 6  CIMIS Region 7  CIMIS Region 8  CIMIS Region 9  \
0               1.0             0.0             0.0             0.0   
1               1.0             0.0             0.0             0.0   
2               1.0             0.0             0.0             0.0   
3               0.0             0.0             0.0             0.0   
4               0.0             0.0             0.0             0.0   
..              ...             ...             ...             ...   
444             0.0             0.0             0.0             0.0   
445             0.0             0.0             0.0             1.0   
446             0.0             0.0             1.0             0.0   
447             0.0             0.0             0.0             0.0   
448             1.0             0.0             0.0             0.0   

     CIMIS Region 10  CIMIS Region 11  
0                0.0              0.0  
1                0.0              0.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              0.0  
..               ...              ...  
444              1.0              0.0  
445              0.0              0.0  
446              0.0              0.0  
447              1.0              0.0  
448              0.0             

In [49]:
from sklearn.model_selection import train_test_split
import numpy as np


X = df.iloc[:,2:109].values
Y = df.iloc[:,1:2].values

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = .1, random_state = 0)

#makes two similar models and then checking error for which one is better

In [50]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree=1) #greater than one yields a HUGE error 
X_poly = poly_reg.fit_transform(X_train)
model = LinearRegression()
model.fit(X_poly, Y_train)

LinearRegression()

In [51]:
sample = (X_test[0].reshape(1,-1))[0]
sample = np.array([sample])
print(sample)

[[0.         0.         0.225      0.43515794 0.57757878 0.80937863
  0.18464667 0.         1.         0.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.      

In [52]:
model.predict(poly_reg.fit_transform(sample))

array([[15680.]])

In [53]:
error = 0
for sample in range(len(X_test)):
    Xarr = ((X_test[sample].reshape(1,-1))[0])
    Xarr = np.array([Xarr])
    yhat = model.predict(poly_reg.fit_transform(Xarr))
    y = np.array([Y_test[sample]])
    if(yhat < 0):
        print("NEGATIVE, yhat = 0")
        yhat = np.array([0])
        
    print(y, yhat)
    error += (yhat - y)**2
    print(error)
    
RMSE = (error/ (len(X_test)))**(1/2)
print(RMSE)

[[10.]] [[15680.]]
[[2.455489e+08]]
[[268.]] [[1344.]]
[[2.46706676e+08]]
[[10.]] [[1920.]]
[[2.50354776e+08]]
[[525.]] [[1024.]]
[[2.50603777e+08]]
[[30.]] [[1792.]]
[[2.53708421e+08]]
NEGATIVE, yhat = 0
[[375.]] [0]
[[2.53849046e+08]]
[[0.]] [[17664.]]
[[5.65865942e+08]]
NEGATIVE, yhat = 0
[[120.]] [0]
[[5.65880342e+08]]
[[328.]] [[256.]]
[[5.65885526e+08]]
[[88.]] [[1600.]]
[[5.6817167e+08]]
NEGATIVE, yhat = 0
[[167.]] [0]
[[5.68199559e+08]]
NEGATIVE, yhat = 0
[[25.]] [0]
[[5.68200184e+08]]
NEGATIVE, yhat = 0
[[2500.]] [0]
[[5.74450184e+08]]
NEGATIVE, yhat = 0
[[258.]] [0]
[[5.74516748e+08]]
NEGATIVE, yhat = 0
[[448.]] [0]
[[5.74717452e+08]]
[[13.]] [[19904.]]
[[9.70369333e+08]]
[[668.]] [[3840.]]
[[9.80430917e+08]]
[[48920.]] [[140544.]]
[[9.37538829e+09]]
[[31.]] [[17536.]]
[[9.68181332e+09]]
[[17.]] [[1728.]]
[[9.68474084e+09]]
NEGATIVE, yhat = 0
[[227.]] [0]
[[9.68479237e+09]]
[[17.]] [[640.]]
[[9.6851805e+09]]
NEGATIVE, yhat = 0
[[55.]] [0]
[[9.68518352e+09]]
[[50.]] [[2496.]]


In [54]:
reg = LinearRegression().fit(X_train,Y_train)

error = 0
for sample in range(len(X_test)):
    Xarr = ((X_test[sample].reshape(1,-1))[0])
    Xarr = np.array([Xarr])
    yhat = reg.predict(Xarr)
    y = np.array([Y_test[sample]])
    if(yhat < 0):
        print("NEGATIVE, yhat = 0")
        yhat = np.array([0])
        
    print(y, yhat)
    error += (yhat - y)**2
    print(error)
    
RMSE = (error/ (len(X_test)))**(1/2)
print(RMSE)


[[10.]] [[15968.]]
[[2.54657764e+08]]
[[268.]] [[1056.]]
[[2.55278708e+08]]
[[10.]] [[2176.]]
[[2.59970264e+08]]
[[525.]] [[768.]]
[[2.60029313e+08]]
[[30.]] [[1536.]]
[[2.62297349e+08]]
NEGATIVE, yhat = 0
[[375.]] [0]
[[2.62437974e+08]]
[[0.]] [[18592.]]
[[6.08100438e+08]]
NEGATIVE, yhat = 0
[[120.]] [0]
[[6.08114838e+08]]
[[328.]] [[832.]]
[[6.08368854e+08]]
[[88.]] [[736.]]
[[6.08788758e+08]]
NEGATIVE, yhat = 0
[[167.]] [0]
[[6.08816647e+08]]
NEGATIVE, yhat = 0
[[25.]] [0]
[[6.08817272e+08]]
NEGATIVE, yhat = 0
[[2500.]] [0]
[[6.15067272e+08]]
NEGATIVE, yhat = 0
[[258.]] [0]
[[6.15133836e+08]]
NEGATIVE, yhat = 0
[[448.]] [0]
[[6.1533454e+08]]
[[13.]] [[20128.]]
[[1.01994776e+09]]
[[668.]] [[3072.]]
[[1.02572698e+09]]
[[48920.]] [[140064.]]
[[9.33295572e+09]]
[[31.]] [[18080.]]
[[9.65872212e+09]]
[[17.]] [[1600.]]
[[9.66122801e+09]]
NEGATIVE, yhat = 0
[[227.]] [0]
[[9.66127954e+09]]
[[17.]] [[192.]]
[[9.66131016e+09]]
NEGATIVE, yhat = 0
[[55.]] [0]
[[9.66131319e+09]]
[[50.]] [[2464.]]

0.2547287751294778

In [55]:
#"model" has a better RMSE then the "reg"

In [56]:
model.coef_

array([[-6.01382700e+14, -1.17692372e+04, -1.00085156e+04,
        -1.85480872e+04, -4.59869243e+03, -1.62480177e+04,
         2.76522249e+03,  1.11806167e+04, -5.91189129e+17,
        -5.91189129e+17,  3.58587076e+17,  2.50439407e+17,
        -8.18972519e+16, -3.06997519e+17,  4.43054060e+17,
         4.63192339e+17,  1.33375334e+17,  6.14314053e+16,
         1.08637331e+17,  8.73188606e+16, -5.27010161e+16,
        -9.50062123e+16,  1.43662766e+17, -1.78471123e+16,
         2.18534961e+17,  6.19293617e+16, -5.31071832e+16,
        -2.26246786e+16,  9.69252899e+16,  2.21372238e+17,
        -1.39690962e+16, -2.08252022e+17, -1.18057568e+17,
         3.93801631e+17,  2.76817978e+17,  1.03715417e+17,
         9.55086399e+16,  1.25645418e+17, -5.01951081e+17,
        -9.22176608e+16, -9.22175076e+16,  9.69584740e+16,
         6.86401753e+16,  7.81338400e+17, -4.10799145e+16,
         9.52409184e+16, -3.44748799e+17, -5.78508699e+17,
         7.15882669e+16, -5.38159877e+16, -3.71786158e+1

In [57]:
model.intercept_

array([3.56353702e+17])