In [60]:
import pandas as pd
import seaborn as sb
import tensorflow as tf

df= pd.read_csv("data/Ca_fire_weather.csv")
df =df.drop(['Unnamed: 0', 'Precip (in)'], axis=1)
df

AcresBurned  ArchiveYear  Days Burned  Precipitation  Temperature  \
0       410203.0          0.0     0.447222       0.075170     0.694110   
1        48920.0          0.0     0.447222       0.075170     0.694110   
2           75.0          0.0     0.511111       0.066545     0.715255   
3          972.0          0.0     0.436111       0.000000     0.000000   
4           90.0          0.0     0.508333       0.092783     0.834265   
..           ...          ...          ...            ...          ...   
444         13.0          1.0     0.002778       0.019330     0.917902   
445         11.0          1.0     0.000000       0.000000     0.831243   
446         11.0          1.0     0.000000       0.000000     0.751425   
447         10.0          1.0     0.000000       0.000000     0.866591   
448         10.0          1.0     0.022222       0.000000     0.713164   

     Humidity  Wind Speed  CalFireIncident 0  CalFireIncident 1  County 0  \
0    0.769694    0.286721                0.0                1.0       0.0   
1    0.769694    0.286721                0.0                1.0       0.0   
2    0.770036    0.283663                0.0                1.0       0.0   
3    0.000000    0.000000                1.0                0.0       0.0   
4    0.591071    0.242949                0.0                1.0       0.0   
..        ...         ...                ...                ...       ...   
444  0.386905    0.336538                0.0                1.0       0.0   
445  0.750000    0.160256                0.0                1.0       0.0   
446  0.916667    0.211538                0.0                1.0       1.0   
447  0.440476    0.198718                0.0                1.0       0.0   
448  0.727513    0.162393                0.0                1.0       0.0   

     ...  CIMIS Region 2  CIMIS Region 3  CIMIS Region 4  CIMIS Region 5  \
0    ...             0.0             0.0             0.0             0.0   
1    ...             0.0             0.0             0.0             0.0   
2    ...             0.0             0.0             0.0             0.0   
3    ...             0.0             0.0             1.0             0.0   
4    ...             0.0             0.0             1.0             0.0   
..   ...             ...             ...             ...             ...   
444  ...             0.0             0.0             0.0             0.0   
445  ...             0.0             0.0             0.0             0.0   
446  ...             0.0             0.0             0.0             0.0   
447  ...             0.0             0.0             0.0             0.0   
448  ...             0.0             0.0             0.0             0.0   

     CIMIS Region 6  CIMIS Region 7  CIMIS Region 8  CIMIS Region 9  \
0               1.0             0.0             0.0             0.0   
1               1.0             0.0             0.0             0.0   
2               1.0             0.0             0.0             0.0   
3               0.0             0.0             0.0             0.0   
4               0.0             0.0             0.0             0.0   
..              ...             ...             ...             ...   
444             0.0             0.0             0.0             0.0   
445             0.0             0.0             0.0             1.0   
446             0.0             0.0             1.0             0.0   
447             0.0             0.0             0.0             0.0   
448             1.0             0.0             0.0             0.0   

     CIMIS Region 10  CIMIS Region 11  
0                0.0              0.0  
1                0.0              0.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              0.0  
..               ...              ...  
444              1.0              0.0  
445              0.0              0.0  
446              0.0              0.0  
447              1.0     

In [61]:
for col in df.columns: 
    print(col)

AcresBurned
ArchiveYear
Days Burned
Precipitation
Temperature
Humidity
Wind Speed
CalFireIncident 0
CalFireIncident 1
County 0
County 1
County 2
County 3
County 4
County 5
County 6
County 7
County 8
County 9
County 10
County 11
County 12
County 13
County 14
County 15
County 16
County 17
County 18
County 19
County 20
County 21
County 22
County 23
County 24
County 25
County 26
County 27
County 28
County 29
County 30
County 31
County 32
County 33
County 34
County 35
County 36
County 37
County 38
County 39
County 40
County 41
Stn Id 0
Stn Id 1
Stn Id 2
Stn Id 3
Stn Id 4
Stn Id 5
Stn Id 6
Stn Id 7
Stn Id 8
Stn Id 9
Stn Id 10
Stn Id 11
Stn Id 12
Stn Id 13
Stn Id 14
Stn Id 15
Stn Id 16
Stn Id 17
Stn Id 18
Stn Id 19
Stn Id 20
Stn Id 21
Stn Id 22
Stn Id 23
Stn Id 24
Stn Id 25
Stn Id 26
Stn Id 27
Stn Id 28
Stn Id 29
Stn Id 30
Stn Id 31
Stn Id 32
Stn Id 33
Stn Id 34
Stn Id 35
Stn Id 36
Stn Id 37
Stn Id 38
Stn Id 39
Stn Id 40
Stn Id 41
Stn Id 42
Stn Id 43
CIMIS Region 0
CIMIS Region 1
CIMIS Region

In [62]:
from sklearn.model_selection import train_test_split
import numpy as np


X = df.iloc[:,1:107].values
Y = df.iloc[:,0:1].values

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = .1, random_state = 0)

#makes two similar models and then checking error for which one is better

In [63]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree=1) #greater than one yields a HUGE error 
X_poly = poly_reg.fit_transform(X_train)
model = LinearRegression()
model.fit(X_poly, Y_train)

LinearRegression()

In [64]:
sample = (X_test[0].reshape(1,-1))[0]
sample = np.array([sample])
print(sample)

[[0.         0.225      0.43515794 0.57757878 0.80937863 0.18464667
  0.         1.         0.         0.         1.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.      

In [65]:
model.predict(poly_reg.fit_transform(sample))

array([[15456.]])

In [66]:
error = 0
for sample in range(len(X_test)):
    Xarr = ((X_test[sample].reshape(1,-1))[0])
    Xarr = np.array([Xarr])
    yhat = model.predict(poly_reg.fit_transform(Xarr))
    y = np.array([Y_test[sample]])
    if(yhat < 0):
        print("NEGATIVE, yhat = 0")
        yhat = np.array([0])
        
    print(y, yhat)
    error += (yhat - y)**2
    print(error)
    
RMSE = (error/ (len(X_test)))**(1/2)
print(RMSE)

[[10.]] [[15456.]]
[[2.38578916e+08]]
[[268.]] [[864.]]
[[2.38934132e+08]]
[[10.]] [[1952.]]
[[2.42705496e+08]]
[[525.]] [[800.]]
[[2.42781121e+08]]
[[30.]] [[1504.]]
[[2.44953797e+08]]
NEGATIVE, yhat = 0
[[375.]] [0]
[[2.45094422e+08]]
[[0.]] [[18208.]]
[[5.76625686e+08]]
NEGATIVE, yhat = 0
[[120.]] [0]
[[5.76640086e+08]]
[[328.]] [[384.]]
[[5.76643222e+08]]
[[88.]] [[288.]]
[[5.76683222e+08]]
NEGATIVE, yhat = 0
[[167.]] [0]
[[5.76711111e+08]]
NEGATIVE, yhat = 0
[[25.]] [0]
[[5.76711736e+08]]
NEGATIVE, yhat = 0
[[2500.]] [0]
[[5.82961736e+08]]
NEGATIVE, yhat = 0
[[258.]] [0]
[[5.830283e+08]]
NEGATIVE, yhat = 0
[[448.]] [0]
[[5.83229004e+08]]
[[13.]] [[19840.]]
[[9.76338933e+08]]
[[668.]] [[2976.]]
[[9.81665797e+08]]
[[48920.]] [[140096.]]
[[9.29472877e+09]]
[[31.]] [[17504.]]
[[9.6000345e+09]]
[[17.]] [[1376.]]
[[9.60188138e+09]]
NEGATIVE, yhat = 0
[[227.]] [0]
[[9.60193291e+09]]
NEGATIVE, yhat = 0
[[17.]] [0]
[[9.6019332e+09]]
NEGATIVE, yhat = 0
[[55.]] [0]
[[9.60193623e+09]]
[[50.]]

In [67]:
reg = LinearRegression().fit(X_train,Y_train)

error = 0
for sample in range(len(X_test)):
    Xarr = ((X_test[sample].reshape(1,-1))[0])
    Xarr = np.array([Xarr])
    yhat = reg.predict(Xarr)
    y = np.array([Y_test[sample]])
    if(yhat < 0):
        print("NEGATIVE, yhat = 0")
        yhat = np.array([0])
        
    print(y, yhat)
    error += (yhat - y)**2
    print(error)
    
RMSE = (error/ (len(X_test)))**(1/2)
print(RMSE)


[[10.]] [[15522.]]
[[2.40622144e+08]]
[[268.]] [[878.]]
[[2.40994244e+08]]
[[10.]] [[1960.]]
[[2.44796744e+08]]
[[525.]] [[802.]]
[[2.44873473e+08]]
[[30.]] [[1574.]]
[[2.47257409e+08]]
NEGATIVE, yhat = 0
[[375.]] [0]
[[2.47398034e+08]]
[[0.]] [[18342.]]
[[5.83826998e+08]]
NEGATIVE, yhat = 0
[[120.]] [0]
[[5.83841398e+08]]
[[328.]] [[478.]]
[[5.83863898e+08]]
[[88.]] [[412.]]
[[5.83968874e+08]]
NEGATIVE, yhat = 0
[[167.]] [0]
[[5.83996763e+08]]
NEGATIVE, yhat = 0
[[25.]] [0]
[[5.83997388e+08]]
NEGATIVE, yhat = 0
[[2500.]] [0]
[[5.90247388e+08]]
NEGATIVE, yhat = 0
[[258.]] [0]
[[5.90313952e+08]]
NEGATIVE, yhat = 0
[[448.]] [0]
[[5.90514656e+08]]
[[13.]] [[19786.]]
[[9.81486185e+08]]
[[668.]] [[3200.]]
[[9.87897209e+08]]
[[48920.]] [[140026.]]
[[9.28820044e+09]]
[[31.]] [[17486.]]
[[9.59287747e+09]]
[[17.]] [[1446.]]
[[9.59491951e+09]]
NEGATIVE, yhat = 0
[[227.]] [0]
[[9.59497104e+09]]
NEGATIVE, yhat = 0
[[17.]] [0]
[[9.59497133e+09]]
NEGATIVE, yhat = 0
[[55.]] [0]
[[9.59497435e+09]]
[[5

In [68]:
#"model" has a better RMSE then the "reg"

In [69]:
model.coef_

array([[-1.39156100e+14, -1.21247461e+04, -2.03573287e+04,
        -2.93685733e+03, -1.64534446e+04,  2.06329194e+03,
         1.20558266e+04, -1.17629604e+17, -1.17629604e+17,
         1.25613237e+16,  9.22776168e+15,  1.34417874e+16,
         3.94890805e+16,  4.02702938e+16, -1.11368145e+16,
         3.13543089e+16, -2.13658233e+16,  5.42459298e+15,
         1.95954068e+16, -3.68322443e+16, -3.56087088e+15,
         4.27505600e+16, -2.75241130e+16,  2.04469319e+16,
        -4.34417324e+16, -2.55399295e+15,  2.26195455e+16,
        -1.23167992e+16, -1.34966696e+16,  2.35465660e+16,
        -1.07802931e+16, -6.85651091e+16, -2.64720397e+17,
         4.76204449e+15,  1.80581826e+16, -8.24359973e+16,
         3.92325169e+16, -5.32301238e+16, -7.63191644e+15,
        -2.41344708e+16,  1.26396314e+16, -7.25565744e+16,
        -9.73707756e+16, -2.97306095e+16,  1.43744557e+16,
         2.87927777e+16, -6.10960385e+16, -5.60641332e+15,
        -1.68585626e+16, -1.74783024e+15,  2.75892801e+1

In [70]:
model.intercept_

array([1.65572541e+17])